### ISSUE TITLE
URL pop-up when hovering on link covers up command line

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#40]
Really annoying on link dense pages like https://news.bbc.co.uk.

**Comment by bovine3dom** [comment]
URL pop-ups are hidden in e01d34a (via userChrome) but I'd rather we had a solution for all users, if at all possible.

**Comment by KrazyCavin** [comment]
Thanks for the inspiration. It's a nice trick to hide it.
Sometimes, URL hint is helpful for me. So I changed userChrome.css to move it to top-left. It feels good now.

**Comment by qoxxxx** [comment]
@krazycavin, would you mind sharing how ? Thanks.

**Comment by KrazyCavin** [comment]
@qoxxxx It't my dumb way, don't mock me
```
statuspanel[type="overLink"]{
        top:54px;
}
```
Put this in userChrome.css

**Comment by joelpet** [comment]
I made the following amendment to @KrazyCavin's suggestion:

```css
statuspanel[type="overLink"] .statuspanel-label {
    border-width: 0 1px 1px 0 !important;
    border-color: rgb(182, 182, 179) !important;
    border-style: solid !important;
}
```
