### ISSUE TITLE
static/themes folder structure

### ISSUE THREAD

**Issue by caputchinefrobles** [cmcaine/tridactyl#481]
I was trying to come up with a new theme and found that the css files were kind of messy in static folder. I managed to reallocate them in order to a better structure:

- static/themes/default/*.css
- static/themes/dark/*.css
- static/themes/othertheme/*.css

Perhaps it could help with a future ~/.tridactyl/themes/ config.

The only problem I see is keeping track of all link hrefs at the html files which are not many right now, but could be as soon as more themes are being created.

Any thoughts?

**Comment by bovine3dom** [comment]
Folder structure seems sane.

Somewhat related while we're tidying up CSS: I don't know very much about CSS, but to me it would make sense to make heavy use of variables:

```css
:root {
    --tridactyl-fg-colour: black;
}

p {
    color: var(--tridactyl-fg-colour)
}

/* dark theme css */
:root {
    --tridactyl-fg-colour: white;
}
```

so that when we make new elements, they will magically get any theme applied to them.

**Comment by caputchinefrobles** [comment]
Yeap. Just like with the dark theme. 

I just don't get enough CSS inheritance to grasp how what should be a sane hierarchy between a new theme and the defaults css, or even if it would be necessary. 

Another "thing" is hardcoding theme selection like hinting.ts:

`       if (hide) {
            this.focused = false
            this.target.classList.remove("TridactylHintElem")
            if (config.get("theme") === "dark") {
                document
                    .querySelector(":root")
                    .classList.remove("TridactylThemeDark")
            }
        } else {
            this.target.classList.add("TridactylHintElem")
            if (config.get("theme") === "dark") {
                document
                    .querySelector(":root")
                    .classList.add("TridactylThemeDark")
            }
        }
`

**Comment by glacambre** [comment]
We might not even need to bother with CSS variables. We could just do this:
```js
let style = document.createElement("style");
style.textContent = "* { background: red !important; }"
document.body.appendChild(style)
```
We can load the textContent through the NativeMessenger or maybe through an XHR to the webextension's files?

In my opinion this would have the advantage of giving full control to users instead of limiting the possibilities to whatever variables we implement.

**Comment by bovine3dom** [comment]
@glacambre the whole point is that the variables would apply to new bits of the Tridactyl UI without us having to update the themes every time.

e.g.
```css
.TridactylAugmentedRealityHints {
    color: var(--tridactyl-fg-colour)
}
```

would magically have the same style as the user's theme. Currently, we would have to go through every theme and fix everything; it makes more sense for me to have them be palettes.

Obviously, there's nothing stopping people writing themes that do specify exactly which things they effect in weird and wonderful ways that we would never have thought to do. I'm just saying that the themes we provide and CSS we use should make maximum use of variables so that they are maintenance free.

**Comment by bovine3dom** [comment]
Ok, so, @caputchinefrobles, I think what we should do is this:

- have a static/css folder that contains all of the default css, something like https://github.com/cmcaine/tridactyl/commit/7cdf49bc74ae0eed9fc221bfdceec56fd336ed8b
- have a static/themes folder that contains a bunch of palettes, each of which looks a bit like this:
```css
:root {
    --tridactyl-fg-colour: pink;
    --tridactyl-bg-colour: green;
    --tridactyl-font-family: "Comic Sans MS";
    --tridactyl-border-colour: yellow;

}
```
- append the user's chosen palette to every web page as in https://stackoverflow.com/questions/11833759/add-stylesheet-to-head-using-javascript-in-body (but without jQuery).


Does that sound sensible to you? Is that something you want to work on?
