### ISSUE TITLE
Make mode indicator disappear on hover

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#565]
As per https://github.com/cmcaine/tridactyl/issues/57#issuecomment-389398985.

I had a go in Firefox's developer tools but couldn't get it to work.

**Comment by glacambre** [comment]
Untested but I believe this could work:
```css
.TridactylStatusIndicator:hover {
    opacity: 0; !important;
    z-index: -3000 !important;
}
```

**Comment by bovine3dom** [comment]
changing the z-index doesn't work even without hover, for me.

**Comment by glacambre** [comment]
This one should work then:
```css
.TridactylStatusIndicator:hover {
    opacity: 0 !important;
    pointer-events: none;
}
```
